### ISSUE TITLE
Question: Does the package do anything different from the original rrule packages, you are also linking to? :)

### ISSUE THREAD

**Issue by MadsStolt** [tkortekaas/rrule_generator#2]

**Comment by tkortekaas** [comment]
Sorry, I completely missed this comment.
This package is meant as a UI which users can use to create their own rrule strings. Think of an agenda app that wants to have people create their own recurring events.
Then those strings can be used by a package such as rrule to actually compute when events should display. My package has nothing to do with those calculations.
In my app I use this package and I use the rrule package. So I can guarantee that this package is compatible with at least that package.
@MadsStolt Does this answer your question?

**Comment by MadsStolt** [comment]
@tkortekaas Yes perfectly. I will try this out instead of writing my own. Thanks :)
