### ISSUE TITLE
BUG: Monthly Repeat Type toggle ("Repeat on" to "Repeat on the") does not trigger onChange

### ISSUE THREAD

**Issue by MadsStolt** [tkortekaas/rrule_generator#3]
When the toggle for Monthly Repeat Type is set to "Repeat on the," and the preset value matches the desired value, the user is unlikely to make any changes. In this scenario, the onChange event is never triggered, causing the application to fail to register the selection and update dependent logic or UI components.

**Comment by tkortekaas** [comment]
Thanks for reporting the issue! I just fixed it and released a new version!
